import type {
  BoardColumn,
  BoardGame,
  CatalogGame,
} from "@/lib/board/board.types";

export const boardColumns: readonly BoardColumn[] = [
  {
    id: "column-backlog",
    key: "backlog",
    title: "Backlog",
    description: "Para quando chegar a hora.",
    order: 0,
  },
  {
    id: "column-playing",
    key: "playing",
    title: "Jogando",
    description: "No seu ritmo agora.",
    order: 1,
  },
  {
    id: "column-paused",
    key: "paused",
    title: "Em pausa",
    description: "Para retomar sem pressa.",
    order: 2,
  },
  {
    id: "column-completed",
    key: "completed",
    title: "Terminados",
    description: "O que ficou com você.",
    order: 3,
  },
  {
    id: "column-dropped",
    key: "dropped",
    title: "Deixados",
    description: "Nem todo jogo precisa continuar.",
    order: 4,
  },
  {
    id: "column-wishlist",
    key: "wishlist",
    title: "Na mira",
    description: "Antes de entrar na fila.",
    order: 5,
  },
] as const;

export const boardStatusLabels = {
  backlog: "Backlog",
  playing: "Jogando",
  paused: "Em pausa",
  completed: "Terminado",
  dropped: "Deixado",
  wishlist: "Na mira",
} as const;

export const mockBoardGames: readonly BoardGame[] = [
  {
    id: "glass-harbor",
    slug: "glass-harbor",
    title: "Porto de vidro",
    coverTone: "night",
    platform: "PlayStation 5",
    status: "backlog",
    position: 0,
    sessions: [],
    releaseYear: 2025,
    tags: ["aventura", "narrativo"],
    shortNote: "Para um fim de semana sem pressa.",
    updatedAt: "2026-07-29",
  },
  {
    id: "paper-moon",
    slug: "paper-moon",
    title: "Lua de papel",
    coverTone: "gold",
    platform: "Nintendo Switch",
    status: "backlog",
    position: 1,
    sessions: [],
    releaseYear: 2024,
    tags: ["puzzle", "indie"],
    updatedAt: "2026-07-22",
  },
  {
    id: "after-winter",
    slug: "after-winter",
    title: "Depois do inverno",
    coverTone: "wine",
    platform: "PC",
    status: "playing",
    position: 0,
    progressPercent: 62,
    sessions: [
      {
        id: "session-after-winter-1",
        playedOn: "2026-07-31",
        durationMinutes: 95,
        progressPercent: 62,
        note: "Ainda pensando naquele encontro no lago.",
      },
    ],
    releaseYear: 2025,
    tags: ["drama", "exploração"],
    shortNote: "Ainda pensando naquele encontro no lago.",
    updatedAt: "2026-07-31",
  },
  {
    id: "low-tide",
    slug: "low-tide",
    title: "Maré baixa",
    coverTone: "forest",
    platform: "PlayStation 5",
    status: "playing",
    position: 1,
    progressPercent: 35,
    sessions: [
      {
        id: "session-low-tide-1",
        playedOn: "2026-07-27",
        durationMinutes: 70,
        progressPercent: 35,
      },
    ],
    releaseYear: 2023,
    tags: ["ação", "mundo aberto"],
    updatedAt: "2026-07-27",
  },
  {
    id: "small-suns",
    slug: "small-suns",
    title: "Pequenos sóis",
    coverTone: "ember",
    platform: "Nintendo Switch",
    status: "paused",
    position: 0,
    progressPercent: 18,
    sessions: [],
    releaseYear: 2024,
    tags: ["plataforma", "leve"],
    shortNote: "Voltar quando sobrar uma noite livre.",
    updatedAt: "2026-07-15",
  },
  {
    id: "salt-road",
    slug: "salt-road",
    title: "A estrada de sal",
    coverTone: "smoke",
    platform: "PC",
    status: "completed",
    position: 0,
    progressPercent: 100,
    sessions: [
      {
        id: "session-salt-road-1",
        playedOn: "2026-07-20",
        durationMinutes: 110,
        progressPercent: 100,
      },
    ],
    rating: 4.5,
    releaseYear: 2025,
    tags: ["rpg", "narrativo"],
    shortNote: "Pequeno, estranho e muito preciso.",
    updatedAt: "2026-07-20",
  },
  {
    id: "signal-loss",
    slug: "signal-loss",
    title: "Sinal perdido",
    coverTone: "night",
    platform: "Xbox Series",
    status: "dropped",
    position: 0,
    progressPercent: 7,
    sessions: [],
    releaseYear: 2024,
    tags: ["terror"],
    shortNote: "A ideia era boa, mas não era o momento.",
    updatedAt: "2026-07-11",
  },
  {
    id: "far-light",
    slug: "far-light",
    title: "Luz distante",
    coverTone: "ember",
    platform: "PlayStation 5",
    status: "wishlist",
    position: 0,
    sessions: [],
    releaseYear: 2026,
    tags: ["ficção científica"],
    updatedAt: "2026-07-30",
  },
] as const;

export const mockCatalogGames: readonly CatalogGame[] = [
  {
    id: "catalog-disco-elysium",
    title: "Disco Elysium",
    releaseYear: 2019,
    platform: "PC",
    coverTone: "wine",
  },
  {
    id: "catalog-outer-wilds",
    title: "Outer Wilds",
    releaseYear: 2019,
    platform: "PlayStation 5",
    coverTone: "night",
  },
  {
    id: "catalog-hades",
    title: "Hades",
    releaseYear: 2020,
    platform: "Nintendo Switch",
    coverTone: "ember",
  },
  {
    id: "catalog-celeste",
    title: "Celeste",
    releaseYear: 2018,
    platform: "Nintendo Switch",
    coverTone: "gold",
  },
  {
    id: "catalog-hollow-knight",
    title: "Hollow Knight",
    releaseYear: 2017,
    platform: "Xbox Series",
    coverTone: "forest",
  },
] as const;
