import type { DiscoverCollection, DiscoverGame, DiscoverReview } from "@/lib/discover/types";

export const discoverGames: readonly DiscoverGame[] = [
  { id: "luz-de-saida", slug: "luz-de-saida", title: "Luz de saída", studio: "Estúdio Pólen", year: 2025, platforms: ["PC", "Switch"], genres: ["Exploração", "Narrativo"], tags: ["Curto", "Melancólico"], duration: "4–5 horas", score: 9.2, summary: "Uma estação vazia, um rádio aceso e o caminho de volta ainda por descobrir.", note: "Para abrir numa noite sem pressa.", coverTone: "ember", featured: true },
  { id: "de-volta-ao-lago", slug: "de-volta-ao-lago", title: "De volta ao lago", studio: "Margem", year: 2024, platforms: ["PC", "PlayStation"], genres: ["Narrativo", "Mistério"], tags: ["Curto", "Atmosférico"], duration: "6–8 horas", score: 9.0, summary: "Um verão antigo reaparece em cartas, fitas e lugares que não ficaram iguais.", note: "Um mistério pequeno, atento aos detalhes.", coverTone: "forest", featured: true },
  { id: "pequenos-sois", slug: "pequenos-sois", title: "Pequenos sóis", studio: "Vaga-lume", year: 2025, platforms: ["PC", "Xbox"], genres: ["Aventura", "Exploração"], tags: ["Contemplativo", "Curto"], duration: "5 horas", score: 8.8, summary: "Acompanhe pequenas luzes por uma cidade que só acorda depois da chuva.", note: "Para trocar urgência por curiosidade.", coverTone: "gold" },
  { id: "mar-aberto", slug: "mar-aberto", title: "Mar aberto", studio: "Rastro", year: 2023, platforms: ["PC", "PlayStation", "Switch"], genres: ["Exploração", "Aventura"], tags: ["Fim de semana", "Livre"], duration: "8–10 horas", score: 8.7, summary: "Navegue entre ilhas pequenas e histórias deixadas à deriva.", note: "Uma viagem que aceita o seu ritmo.", coverTone: "night" },
  { id: "em-duas-maos", slug: "em-duas-maos", title: "Em duas mãos", studio: "Bilateral", year: 2024, platforms: ["PC", "PlayStation"], genres: ["Cooperativo", "Puzzle"], tags: ["Cooperativo", "Curto"], duration: "3–4 horas", score: 8.9, summary: "Dois jogadores dividem o mesmo mapa, mas nunca enxergam tudo.", note: "Bom para chamar alguém sem assumir a noite inteira.", coverTone: "ember" },
  { id: "depois-do-inverno", slug: "depois-do-inverno", title: "Depois do inverno", studio: "Campo Aberto", year: 2022, platforms: ["PC", "Switch"], genres: ["Narrativo", "Aventura"], tags: ["Íntimo", "Calmo"], duration: "7 horas", score: 9.1, summary: "Uma vila volta a falar sobre o que tentou esquecer quando a neve baixa.", note: "Para quem quer uma história que fica um pouco depois.", coverTone: "forest" },
];

export const discoverCollections: readonly DiscoverCollection[] = [
  { id: "fim-de-semana", slug: "para-terminar-no-fim-de-semana", title: "Para terminar no fim de semana", description: "Jogos fechados, com tempo para entrar e sair sem deixar nada pela metade.", gameIds: ["luz-de-saida", "em-duas-maos", "mar-aberto"], mood: "6–10 horas" },
  { id: "depois-de-longo", slug: "depois-de-um-jogo-longo", title: "Depois de um jogo longo", description: "Histórias menores para recuperar a vontade de começar algo novo.", gameIds: ["pequenos-sois", "de-volta-ao-lago", "luz-de-saida"], mood: "Pausa boa" },
  { id: "junto", slug: "para-jogar-junto", title: "Para jogar junto", description: "Experiências que funcionam melhor quando alguém divide o sofá ou a conversa.", gameIds: ["em-duas-maos", "mar-aberto"], mood: "Dois controles" },
];

export const discoverReviews: readonly DiscoverReview[] = [
  { id: "review-lago", slug: "um-misterio-que-sabe-parar", gameId: "de-volta-ao-lago", author: "Nina Moreira", rating: 5, excerpt: "Ele sabe a hora de não explicar tudo. Saí pensando mais nos espaços entre as cenas do que nas respostas.", body: "De volta ao lago confia no silêncio e no olhar de quem joga. É um mistério que sabe parar antes de virar exercício de explicação.", publishedAt: "Há 2 dias" },
  { id: "review-luz", slug: "uma-noite-bem-gasta", gameId: "luz-de-saida", author: "Caio Alves", rating: 4.5, excerpt: "Uma noite bem gasta. Pequeno, preciso e sem uma cena sobrando.", body: "Luz de saída é breve, mas não apressado. Cada lugar tem a medida certa para você ficar mais um pouco.", publishedAt: "Há 5 dias" },
  { id: "review-inverno", slug: "o-que-fica-depois", gameId: "depois-do-inverno", author: "Lara Sato", rating: 5, excerpt: "Não é sobre consertar o passado. É sobre aprender a andar perto dele.", body: "Depois do inverno encontra delicadeza em pessoas que ainda não sabem como recomeçar. É um jogo que continua fazendo companhia depois dos créditos.", publishedAt: "Há 1 semana" },
];
