import type {
  DiscoverCollection,
  DiscoverGame,
  DiscoverReview,
} from "@/lib/discover/types";

const initialDiscoverGames: readonly DiscoverGame[] = [
  {
    id: "luz-de-saida",
    slug: "luz-de-saida",
    title: "Luz de saída",
    studio: "Estúdio Pólen",
    year: 2025,
    platforms: ["PC", "Switch"],
    genres: ["Exploração", "Narrativo"],
    tags: ["Curto", "Melancólico"],
    duration: "4–5 horas",
    score: 9.2,
    summary:
      "Uma estação vazia, um rádio aceso e o caminho de volta ainda por descobrir.",
    note: "Para abrir numa noite sem pressa.",
    coverTone: "ember",
    featured: true,
  },
  {
    id: "de-volta-ao-lago",
    slug: "de-volta-ao-lago",
    title: "De volta ao lago",
    studio: "Margem",
    year: 2024,
    platforms: ["PC", "PlayStation"],
    genres: ["Narrativo", "Mistério"],
    tags: ["Curto", "Atmosférico"],
    duration: "6–8 horas",
    score: 9.0,
    summary:
      "Um verão antigo reaparece em cartas, fitas e lugares que não ficaram iguais.",
    note: "Um mistério pequeno, atento aos detalhes.",
    coverTone: "forest",
    featured: true,
  },
  {
    id: "pequenos-sois",
    slug: "pequenos-sois",
    title: "Pequenos sóis",
    studio: "Vaga-lume",
    year: 2025,
    platforms: ["PC", "Xbox"],
    genres: ["Aventura", "Exploração"],
    tags: ["Contemplativo", "Curto"],
    duration: "5 horas",
    score: 8.8,
    summary:
      "Acompanhe pequenas luzes por uma cidade que só acorda depois da chuva.",
    note: "Para trocar urgência por curiosidade.",
    coverTone: "gold",
  },
  {
    id: "mar-aberto",
    slug: "mar-aberto",
    title: "Mar aberto",
    studio: "Rastro",
    year: 2023,
    platforms: ["PC", "PlayStation", "Switch"],
    genres: ["Exploração", "Aventura"],
    tags: ["Fim de semana", "Livre"],
    duration: "8–10 horas",
    score: 8.7,
    summary: "Navegue entre ilhas pequenas e histórias deixadas à deriva.",
    note: "Uma viagem que aceita o seu ritmo.",
    coverTone: "night",
  },
  {
    id: "em-duas-maos",
    slug: "em-duas-maos",
    title: "Em duas mãos",
    studio: "Bilateral",
    year: 2024,
    platforms: ["PC", "PlayStation"],
    genres: ["Cooperativo", "Puzzle"],
    tags: ["Cooperativo", "Curto"],
    duration: "3–4 horas",
    score: 8.9,
    summary: "Dois jogadores dividem o mesmo mapa, mas nunca enxergam tudo.",
    note: "Bom para chamar alguém sem assumir a noite inteira.",
    coverTone: "ember",
  },
  {
    id: "depois-do-inverno",
    slug: "depois-do-inverno",
    title: "Depois do inverno",
    studio: "Campo Aberto",
    year: 2022,
    platforms: ["PC", "Switch"],
    genres: ["Narrativo", "Aventura"],
    tags: ["Íntimo", "Calmo"],
    duration: "7 horas",
    score: 9.1,
    summary:
      "Uma vila volta a falar sobre o que tentou esquecer quando a neve baixa.",
    note: "Para quem quer uma história que fica um pouco depois.",
    coverTone: "forest",
  },
];

const additionalDiscoverGames: readonly DiscoverGame[] = [
  {
    id: "jardim-de-fio",
    slug: "jardim-de-fio",
    title: "Jardim de fio",
    studio: "Linha d’água",
    year: 2025,
    platforms: ["PC", "Switch"],
    genres: ["Puzzle", "Exploração"],
    tags: ["Curto", "Calmo"],
    duration: "4 horas",
    score: 8.6,
    summary: "Conecte jardins suspensos antes que a cidade acorde.",
    note: "Um quebra-cabeça para ir devagar.",
    coverTone: "gold",
  },
  {
    id: "rua-do-sol",
    slug: "rua-do-sol",
    title: "Rua do sol",
    studio: "Norte Sul",
    year: 2024,
    platforms: ["PC", "Xbox"],
    genres: ["Aventura", "Narrativo"],
    tags: ["Atmosférico"],
    duration: "9 horas",
    score: 8.5,
    summary: "Uma vizinhança inteira guarda pequenos caminhos de volta.",
    note: "Histórias que cabem numa caminhada.",
    coverTone: "ember",
  },
  {
    id: "orbita-baixa",
    slug: "orbita-baixa",
    title: "Órbita baixa",
    studio: "Gravidade",
    year: 2023,
    platforms: ["PC", "PlayStation"],
    genres: ["Exploração", "Puzzle"],
    tags: ["Livre"],
    duration: "10 horas",
    score: 8.4,
    summary: "Mapeie um satélite onde nada permanece no mesmo lugar.",
    note: "Para observar antes de agir.",
    coverTone: "night",
  },
  {
    id: "casa-de-vento",
    slug: "casa-de-vento",
    title: "Casa de vento",
    studio: "Aragem",
    year: 2022,
    platforms: ["PC", "Switch"],
    genres: ["Narrativo", "Exploração"],
    tags: ["Íntimo"],
    duration: "6 horas",
    score: 8.3,
    summary: "Uma casa muda de cômodo conforme as lembranças chegam.",
    note: "Pequeno e cheio de detalhes.",
    coverTone: "forest",
  },
  {
    id: "linha-de-chegada",
    slug: "linha-de-chegada",
    title: "Linha de chegada",
    studio: "Ponto final",
    year: 2025,
    platforms: ["PC", "PlayStation"],
    genres: ["Cooperativo", "Aventura"],
    tags: ["Cooperativo"],
    duration: "5 horas",
    score: 8.2,
    summary: "Dois caminhos, uma mesma linha de chegada.",
    note: "Melhor quando jogado acompanhado.",
    coverTone: "ember",
  },
  {
    id: "marcas-na-neve",
    slug: "marcas-na-neve",
    title: "Marcas na neve",
    studio: "Branco Norte",
    year: 2024,
    platforms: ["PC", "Xbox"],
    genres: ["Exploração", "Narrativo"],
    tags: ["Melancólico"],
    duration: "8 horas",
    score: 8.1,
    summary: "Siga rastros que o inverno ainda não conseguiu apagar.",
    note: "Uma travessia silenciosa.",
    coverTone: "night",
  },
  {
    id: "quase-domingo",
    slug: "quase-domingo",
    title: "Quase domingo",
    studio: "Vaga-lume",
    year: 2023,
    platforms: ["PC", "Switch"],
    genres: ["Narrativo", "Aventura"],
    tags: ["Curto"],
    duration: "3 horas",
    score: 8.0,
    summary: "Uma tarde comum se recusa a terminar.",
    note: "Para uma pausa breve.",
    coverTone: "gold",
  },
  {
    id: "ponto-de-encontro",
    slug: "ponto-de-encontro",
    title: "Ponto de encontro",
    studio: "Bilateral",
    year: 2022,
    platforms: ["PC", "PlayStation"],
    genres: ["Cooperativo", "Puzzle"],
    tags: ["Curto", "Cooperativo"],
    duration: "4 horas",
    score: 7.9,
    summary: "Encontre alguém no mapa que muda a cada tentativa.",
    note: "Uma boa desculpa para jogar junto.",
    coverTone: "forest",
  },
  {
    id: "cidade-submersa",
    slug: "cidade-submersa",
    title: "Cidade submersa",
    studio: "Rastro",
    year: 2025,
    platforms: ["PC", "Xbox"],
    genres: ["Exploração", "Aventura"],
    tags: ["Atmosférico"],
    duration: "12 horas",
    score: 8.9,
    summary: "Uma cidade inteira reaparece quando a maré baixa.",
    note: "Para perder algumas horas.",
    coverTone: "night",
  },
  {
    id: "cartas-ao-norte",
    slug: "cartas-ao-norte",
    title: "Cartas ao norte",
    studio: "Margem",
    year: 2024,
    platforms: ["PC", "Switch"],
    genres: ["Narrativo", "Puzzle"],
    tags: ["Íntimo"],
    duration: "5 horas",
    score: 8.7,
    summary: "Decifre cartas que chegaram tarde demais.",
    note: "Um mistério feito de papel.",
    coverTone: "gold",
  },
];

export const discoverGames: readonly DiscoverGame[] = [
  ...initialDiscoverGames,
  ...additionalDiscoverGames,
];

export const discoverCollections: readonly DiscoverCollection[] = [
  {
    id: "fim-de-semana",
    slug: "para-terminar-no-fim-de-semana",
    title: "Para terminar no fim de semana",
    description:
      "Jogos fechados, com tempo para entrar e sair sem deixar nada pela metade.",
    gameIds: ["luz-de-saida", "em-duas-maos", "mar-aberto"],
    mood: "6–10 horas",
    subtitle: "Ritmo de fim de semana",
    tags: ["Curto", "Aventura"],
    platforms: ["PC", "Switch", "PlayStation"],
    curator: "Equipe Backbit",
    curatorType: "Editorial",
    popularity: 96,
    rating: 4.8,
    updatedAt: "2026-07-28",
    featured: true,
    coverTone: "ember",
  },
  {
    id: "depois-de-longo",
    slug: "depois-de-um-jogo-longo",
    title: "Depois de um jogo longo",
    description:
      "Histórias menores para recuperar a vontade de começar algo novo.",
    gameIds: ["pequenos-sois", "de-volta-ao-lago", "luz-de-saida"],
    mood: "Pausa boa",
    subtitle: "Recomeços menores",
    tags: ["Narrativo", "Calmo"],
    platforms: ["PC", "Switch"],
    curator: "Nina Moreira",
    curatorType: "Crítica",
    popularity: 89,
    rating: 4.7,
    updatedAt: "2026-07-25",
    featured: true,
    coverTone: "forest",
  },
  {
    id: "junto",
    slug: "para-jogar-junto",
    title: "Para jogar junto",
    description:
      "Experiências que funcionam melhor quando alguém divide o sofá ou a conversa.",
    gameIds: ["em-duas-maos", "mar-aberto"],
    mood: "Dois controles",
    subtitle: "Sofá, conversa e cooperação",
    tags: ["Cooperativo", "Puzzle"],
    platforms: ["PC", "PlayStation"],
    curator: "Comunidade Backbit",
    curatorType: "Comunidade",
    popularity: 92,
    rating: 4.9,
    updatedAt: "2026-07-21",
    coverTone: "gold",
  },
  {
    id: "chuva",
    slug: "para-ouvir-a-chuva",
    title: "Para ouvir a chuva",
    subtitle: "Uma tarde sem agenda",
    description:
      "Jogos que aceitam passos lentos, janelas abertas e uma atenção mais quieta.",
    gameIds: ["pequenos-sois", "depois-do-inverno", "casa-de-vento"],
    mood: "Contemplativo",
    tags: ["Calmo", "Exploração"],
    platforms: ["PC", "Switch"],
    curator: "Equipe Backbit",
    curatorType: "Editorial",
    popularity: 84,
    rating: 4.6,
    updatedAt: "2026-07-18",
    coverTone: "forest",
  },
  {
    id: "primeiro",
    slug: "melhor-lugar-para-comecar",
    title: "Um bom primeiro jogo",
    subtitle: "Portas de entrada",
    description:
      "Experiências acolhedoras para voltar a jogar ou apresentar alguém a novos mundos.",
    gameIds: ["luz-de-saida", "jardim-de-fio", "quase-domingo"],
    mood: "Começar leve",
    tags: ["Curto", "Narrativo"],
    platforms: ["PC", "Xbox", "Switch"],
    curator: "Caio Alves",
    curatorType: "Crítica",
    popularity: 82,
    rating: 4.5,
    updatedAt: "2026-07-16",
    coverTone: "gold",
  },
  {
    id: "inverno",
    slug: "noites-de-inverno",
    title: "Noites de inverno",
    subtitle: "Luzes acesas depois das seis",
    description:
      "Mistérios e travessias para quando o lado de fora pede para esperar.",
    gameIds: ["marcas-na-neve", "orbita-baixa", "de-volta-ao-lago"],
    mood: "Melancólico",
    tags: ["Mistério", "Narrativo"],
    platforms: ["PC", "Xbox", "PlayStation"],
    curator: "Comunidade Backbit",
    curatorType: "Comunidade",
    popularity: 79,
    rating: 4.5,
    updatedAt: "2026-07-12",
    coverTone: "night",
  },
  {
    id: "intervalo",
    slug: "entre-uma-coisa-e-outra",
    title: "Entre uma coisa e outra",
    subtitle: "Sessões de uma hora",
    description:
      "Pequenos lugares para visitar no intervalo, sem a obrigação de ficar até tarde.",
    gameIds: ["quase-domingo", "jardim-de-fio", "ponto-de-encontro"],
    mood: "Sessão curta",
    tags: ["Curto", "Puzzle"],
    platforms: ["PC", "Switch", "PlayStation"],
    curator: "Equipe Backbit",
    curatorType: "Editorial",
    popularity: 76,
    rating: 4.4,
    updatedAt: "2026-07-09",
    coverTone: "ember",
  },
  {
    id: "mar",
    slug: "mapas-para-se-perder",
    title: "Mapas para se perder",
    subtitle: "Sem rota obrigatória",
    description:
      "Mundos que devolvem a curiosidade de dobrar uma esquina só para ver o que há depois.",
    gameIds: ["mar-aberto", "cidade-submersa", "orbita-baixa"],
    mood: "Livre",
    tags: ["Exploração", "Aventura"],
    platforms: ["PC", "Xbox", "PlayStation"],
    curator: "Lara Sato",
    curatorType: "Crítica",
    popularity: 88,
    rating: 4.7,
    updatedAt: "2026-07-05",
    coverTone: "night",
  },
  {
    id: "cartas",
    slug: "historia-em-pequenas-coisas",
    title: "História em pequenas coisas",
    subtitle: "Cartas, cômodos e rastros",
    description:
      "Narrativas que se encontram nas margens: objetos, pausas e lembranças deixadas pelo caminho.",
    gameIds: ["cartas-ao-norte", "casa-de-vento", "rua-do-sol"],
    mood: "Íntimo",
    tags: ["Narrativo", "Atmosférico"],
    platforms: ["PC", "Switch", "Xbox"],
    curator: "Comunidade Backbit",
    curatorType: "Comunidade",
    popularity: 73,
    rating: 4.4,
    updatedAt: "2026-07-02",
    coverTone: "forest",
  },
];

export const discoverReviews: readonly DiscoverReview[] = [
  {
    id: "review-lago",
    slug: "um-misterio-que-sabe-parar",
    gameId: "de-volta-ao-lago",
    author: "Nina Moreira",
    rating: 5,
    excerpt:
      "Ele sabe a hora de não explicar tudo. Saí pensando mais nos espaços entre as cenas do que nas respostas.",
    body: "De volta ao lago confia no silêncio e no olhar de quem joga. É um mistério que sabe parar antes de virar exercício de explicação.",
    publishedAt: "Há 2 dias",
  },
  {
    id: "review-luz",
    slug: "uma-noite-bem-gasta",
    gameId: "luz-de-saida",
    author: "Caio Alves",
    rating: 4.5,
    excerpt: "Uma noite bem gasta. Pequeno, preciso e sem uma cena sobrando.",
    body: "Luz de saída é breve, mas não apressado. Cada lugar tem a medida certa para você ficar mais um pouco.",
    publishedAt: "Há 5 dias",
  },
  {
    id: "review-inverno",
    slug: "o-que-fica-depois",
    gameId: "depois-do-inverno",
    author: "Lara Sato",
    rating: 5,
    excerpt:
      "Não é sobre consertar o passado. É sobre aprender a andar perto dele.",
    body: "Depois do inverno encontra delicadeza em pessoas que ainda não sabem como recomeçar. É um jogo que continua fazendo companhia depois dos créditos.",
    publishedAt: "Há 1 semana",
  },
];
